# Generated by Django 4.0.4 on 2022-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WalletDetailDump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=256)),
                ("symbol", models.CharField(max_length=256)),
                ("network", models.CharField(max_length=256)),
                ("strength", models.SmallIntegerField()),
                ("entropy", models.CharField(max_length=256)),
                ("mnemonic", models.CharField(max_length=256)),
                ("language", models.CharField(max_length=256)),
                ("passphrase", models.CharField(max_length=256)),
                ("seed", models.CharField(max_length=256)),
                ("root_xprivate_key", models.CharField(max_length=256)),
                ("root_xpublic_key", models.CharField(max_length=256)),
                ("xprivate_key", models.CharField(max_length=256)),
                ("xpublic_key", models.CharField(max_length=256)),
                ("uncompressed", models.CharField(max_length=256)),
                ("compressed", models.CharField(max_length=256)),
                ("chain_code", models.CharField(max_length=256)),
                ("private_key", models.CharField(max_length=256)),
                ("public_key", models.CharField(max_length=256)),
                ("wif", models.CharField(max_length=256)),
                ("finger_print", models.CharField(max_length=256)),
                ("semantic", models.CharField(max_length=256)),
                ("path", models.CharField(max_length=256)),
                ("hash", models.CharField(max_length=256)),
                ("addresses", models.CharField(max_length=256)),
            ],
        ),
    ]
