# Generated by Django 4.0.4 on 2022-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletdetaildump",
            name="passphrase",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
