# Generated by Django 4.0.4 on 2022-12-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_walletdetaildump_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletdetaildump",
            name="addresses",
        ),
        migrations.CreateModel(
            name="Addresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p2pkh", models.CharField(max_length=256)),
                ("p2sh", models.CharField(max_length=256)),
                ("p2wpkh", models.CharField(max_length=256)),
                ("p2wpkh_in_p2sh", models.CharField(max_length=256)),
                ("p2wsh", models.CharField(max_length=256)),
                ("p2wsh_in_p2sh", models.CharField(max_length=256)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.walletdetaildump",
                    ),
                ),
            ],
        ),
    ]
