# Generated by Django 4.0.4 on 2022-12-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_remove_walletdetaildump_addresses_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="wallet.walletdetaildump",
            ),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="chain_code",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="entropy",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="language",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="mnemonic",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="root_xprivate_key",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="root_xpublic_key",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="seed",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="semantic",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="strength",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="xprivate_key",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="walletdetaildump",
            name="xpublic_key",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
