# Generated by Django 4.0.4 on 2022-12-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
