# Generated by Django 4.0.4 on 2022-12-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_transaction_amount_transaction_currency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
